package dev.langchain4j.model.chat.response;

import dev.langchain4j.agent.tool.ToolExecutionRequest;
import dev.langchain4j.data.message.AiMessage;
import dev.langchain4j.model.chat.StreamingChatModel;

/**
 * Represents a handler for a {@link StreamingChatModel} response.
 *
 * @see StreamingChatModel
 */
public interface StreamingChatResponseHandler {

    /**
     * Invoked each time the model generates a partial response (usually a single token) in a textual response.
     * If the model decides to execute a tool instead, this method will not be invoked;
     * {@link #onCompleteResponse} will be invoked instead.
     *
     * @param partialResponse The partial response (usually a single token), which is a part of the complete response.
     */
    void onPartialResponse(String partialResponse);

    /**
     * Invoked each time the model generates a partial tool execution request (a streaming fragment) in a tool call response.
     * Can be called multiple times for a single tool execution request, and for multiple tool executions.
     *
     * @param index                     The index of the tool execution request within the current response.
     * @param partialToolExecutionRequest The partial tool execution request fragment.
     */
    default void onPartialToolExecutionRequest(int index, ToolExecutionRequest partialToolExecutionRequest) {
    }

    /**
     * Invoked as soon as a single tool execution request is complete.
     * Can be called multiple times if the model requests multiple tool executions.
     *
     * @param index                      The index of the tool execution request within the current response.
     * @param completeToolExecutionRequest The complete tool execution request.
     */
    default void onCompleteToolExecutionRequest(int index, ToolExecutionRequest completeToolExecutionRequest) {
    }

    /**
     * Invoked when the model has finished streaming a response.
     * If the model requests the execution of one or multiple tools,
     * this can be accessed via {@link ChatResponse#aiMessage()} -> {@link AiMessage#toolExecutionRequests()}.
     *
     * @param completeResponse The complete response generated by the model.
     *                         For textual responses, it contains all tokens from {@link #onPartialResponse} concatenated.
     */
    void onCompleteResponse(ChatResponse completeResponse);

    /**
     * This method is invoked when an error occurs during streaming.
     *
     * @param error The error that occurred
     */
    void onError(Throwable error);
}
